//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictAndTaintOptions) DeepCopyInto(out *EvictAndTaintOptions) {
	*out = *in
	if in.TaintDuration != nil {
		in, out := &in.TaintDuration, &out.TaintDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictAndTaintOptions.
func (in *EvictAndTaintOptions) DeepCopy() *EvictAndTaintOptions {
	if in == nil {
		return nil
	}
	out := new(EvictAndTaintOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IORemediationPolicy) DeepCopyInto(out *IORemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IORemediationPolicy.
func (in *IORemediationPolicy) DeepCopy() *IORemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(IORemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IORemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IORemediationPolicyList) DeepCopyInto(out *IORemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IORemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IORemediationPolicyList.
func (in *IORemediationPolicyList) DeepCopy() *IORemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(IORemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IORemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IORemediationPolicySpec) DeepCopyInto(out *IORemediationPolicySpec) {
	*out = *in
	in.TargetPodSelector.DeepCopyInto(&out.TargetPodSelector)
	if in.EvictAndTaintConfig != nil {
		in, out := &in.EvictAndTaintConfig, &out.EvictAndTaintConfig
		*out = new(EvictAndTaintOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.MigrateStorageConfig != nil {
		in, out := &in.MigrateStorageConfig, &out.MigrateStorageConfig
		*out = new(MigrateStorageOptions)
		**out = **in
	}
	if in.ScaleUpConfig != nil {
		in, out := &in.ScaleUpConfig, &out.ScaleUpConfig
		*out = new(ScaleUpOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IORemediationPolicySpec.
func (in *IORemediationPolicySpec) DeepCopy() *IORemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(IORemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IORemediationPolicyStatus) DeepCopyInto(out *IORemediationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IORemediationPolicyStatus.
func (in *IORemediationPolicyStatus) DeepCopy() *IORemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(IORemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateStorageOptions) DeepCopyInto(out *MigrateStorageOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateStorageOptions.
func (in *MigrateStorageOptions) DeepCopy() *MigrateStorageOptions {
	if in == nil {
		return nil
	}
	out := new(MigrateStorageOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleUpOptions) DeepCopyInto(out *ScaleUpOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleUpOptions.
func (in *ScaleUpOptions) DeepCopy() *ScaleUpOptions {
	if in == nil {
		return nil
	}
	out := new(ScaleUpOptions)
	in.DeepCopyInto(out)
	return out
}
