apiVersion: autoremediation.tfg.local/v1alpha1
kind: IORemediationPolicy
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: ioremediationpolicy-sample
spec:
  # TODO(user): Add fields here
